### ISSUE TITLE
Is it possible to run it headless instead of headful?

### ISSUE THREAD

**Issue by Muratcol** [Flam3rboy/puppeteer-stream#40] opened 2022-03-03 13:21 UTC
I am using WSL2 and puppeteer is not working headful.  Throws the following error:

```
/home/muratcolyaran/devops/practice/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:237
            reject(new Error([
                   ^

Error: Failed to launch the browser process!
[20057:20057:0303/161449.433072:ERROR:ozone_platform_x11.cc(234)] Missing X server or $DISPLAY
[20057:20057:0303/161449.433114:ERROR:env.cc(225)] The platform failed to initialize.  Exiting.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/muratcolyaran/devops/practice/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:237:20)
    at ChildProcess.<anonymous> (/home/muratcolyaran/devops/practice/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:228:79)
    at ChildProcess.emit (node:events:402:35)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
```

Can we update the package to work also headless? 

Anyone have a recommendation?

**Comment by Flam3rboy** [comment] 2022-03-03 13:39
duplicate of #4

**Closed by Flam3rboy** 2022-03-03 13:39 UTC

**Comment by Flam3rboy** [comment] 2022-03-03 13:40
Tho you can setup an X-Server for wsl. Sometime ago I've managed to setup the xfce desktop environment on wsl, but I can't find the guide again.
Search for ``wsl setup xserver`` or try this guide: https://medium.com/javarevisited/using-wsl-2-with-x-server-linux-on-windows-a372263533c3
